# Generated by Django 5.1 on 2024-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='storyline',
            field=models.TextField(max_length=200),
        ),
    ]
